trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - task: JfrogCliV2@1
    inputs:
      jfrogPlatformConnection: 'hts2'
      command: |
        jf audit 

  - task: JFrogAudit@1
    inputs:
      xrayConnection: 'hts2xray'
      watchesSource: 'none'
      licenses: false
