name: "Frogbot Scan Pull Request"
on:
  pull_request_target:
    types: [opened, synchronize]
  push:
    branches:
      - '*'
permissions:
  pull-requests: write
  contents: read
jobs:
  scan-pull-request:
    runs-on: ubuntu-latest
    environment: frogbot
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Add this step

      - uses: jfrog/frogbot@v2
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Add any other environment variables as needed
